name: Run Bats Tests

# Trigger the workflow on push events to cli-tips.sh
on:
  push:
    paths:
      - "cli-tips.sh"

  # For debugging ğŸ›ğŸ”
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          sparse-checkout: |
            tests/
            cli-tips.sh

      - name: ğŸ§ª Run Bats Tests
        run: npx bats tests/cli-tips.bats
