name: Run Bats Tests

# Trigger the workflow on push events to cli-tips.sh
on:
  push:
    paths:
      - "cli-tips.sh"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: âš™ï¸ Install dependencies
        run: sudo apt install parallels

      - name: ğŸ§ª Run Bats Tests
        run: npx bats test/cli-tips.bats --jobs $(nproc)
